# Generated by Django 2.1.3 on 2018-11-21 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SpotMe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='course_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(default='sessn', max_length=5)),
                ('course_session_info', models.CharField(default='', max_length=1000)),
                ('semester', models.CharField(choices=[('FALL', 'Fall'), ('AUTUMN', 'Autumn')], max_length=10)),
                ('year', models.IntegerField(choices=[(2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)])),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SpotMe.course')),
            ],
        ),
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('lecture_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('lecture_title', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.course_session')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SpotMe.course_session')),
            ],
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_pic',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='takes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.student'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.location'),
        ),
        migrations.AddField(
            model_name='course_session',
            name='course_instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SpotMe.instructor'),
        ),
    ]
