# Generated by Django 2.1.3 on 2018-11-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotMe', '0002_auto_20181126_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='end_date',
            new_name='lecture_date',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_date',
        ),
    ]
