# Generated by Django 2.1.3 on 2018-11-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotMe', '0002_auto_20181121_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_session',
            name='session_token',
            field=models.CharField(default='sessn', max_length=10),
        ),
    ]
