# Generated by Django 2.1.3 on 2018-11-21 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpotMe', '0003_auto_20181121_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.DateTimeField(default=datetime.datetime.now)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.student')),
            ],
        ),
        migrations.CreateModel(
            name='router',
            fields=[
                ('BSSID', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('SSID', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='router_location_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_strength', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.location')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.router')),
            ],
        ),
        migrations.CreateModel(
            name='router_location_statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.location')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.router')),
            ],
        ),
        migrations.CreateModel(
            name='tracking_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.attendance')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpotMe.location')),
            ],
        ),
    ]
