# Generated by Django 2.1.3 on 2018-11-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotMe', '0004_auto_20181126_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_session',
            name='attendance_time',
            field=models.IntegerField(default=15),
        ),
    ]
