# Generated by Django 2.1.3 on 2018-11-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotMe', '0005_course_session_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_flag',
            field=models.IntegerField(default=0),
        ),
    ]
