# Generated by Django 2.1.3 on 2018-11-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotMe', '0005_auto_20181121_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_title',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
