# Generated by Django 2.1.3 on 2018-11-27 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotMe', '0006_attendance_attendance_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_flag',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lecture')},
        ),
    ]
