# Generated by Django 2.1.3 on 2018-11-25 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SpotMe', '0007_colaborators'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='colaborators',
            new_name='collaborator',
        ),
    ]
