# Generated by Django 2.1.3 on 2018-11-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotMe', '0010_auto_20181125_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='router_location_statistic',
            name='Max',
            field=models.FloatField(default=-100000),
        ),
        migrations.AddField(
            model_name='router_location_statistic',
            name='avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='router_location_statistic',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='router_location_statistic',
            name='var',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='course_session',
            unique_together={('session_token', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='router_location_statistic',
            unique_together={('location', 'router')},
        ),
    ]
